== Chapter 1 : Introducing React

Learning using _Carl Rippon's  Learn React with TypeScript, A beginner's guide to reactive web development with React 18 and TypeScript._

=== Package Managers

*Npm* will create node modules globally, if you use some node packages frequently on most of the application you should go for npm.

*npx* locally installs all node packages for a specific project.

*Yarn* is, like NPM, a package manager for Node.JS. Yarn is a different package, but faster than npm and npx. Yarn is built by Facebook. It's faster and has more features than NPM. Their main selling points are:

* *Security*
    ** With `yarn.lock` file (similar to NPM's `npm-shrinkwrap.json`) all dependencies are locked on the exact version. So, you don't have that “But it works on my machine” struggles anymore. Everyone has the same versions locked in `yarn.lock` file
* *Speed*
** Yarn uses (fast) proxies and (offline) caching to deliver your modules faster.

=== Create a Project from scratch

Using https://www.npmjs.com[npm] and https://vitejs.dev[vite] a default structure for a React project is easy to generate.

[source]
----
> npm create vite@latest #create react project
----

Choose to create a React project with TypeScript + SWC. https://swc.rs[SWC] SWC is an extensible Rust-based platform for the next generation of fast developer tools, that can be used for both compilation and bundling. For compilation, it takes JavaScript / TypeScript files using modern JavaScript features and outputs valid code that is supported by all major browsers.

After generating the project run:

[source]
----
> npm install
----

Run the app by executing `npm run dev` in a terminal.

Run `npm run lint` to verify your app syntax.

*NOTE:* Transpilers are also known as source-to-source compilers. So in essence they are a subset of compilers which take in a source code file and convert it to another source code file in some other language or a different version of the same language. The output is generally understandable by a human. This output still has to go through a compiler or interpreter to be able to run on the machine.

* JSX(**J**ava**S**cript **X**ML) is a JavaScript syntax extension. This means that it doesn't execute directly in the browser – it needs to be transpiled to JavaScript first. A popular tool that can transpile JSX is called Babel.
* A React app is structured in a tree of React components and DOM elements.

[source, typescriptjsx]
----
function App() {
  return (
 // --- JSX bit ----
    <div className="App">
      <Alert type="information" heading="Success">
        Everything is really good!
      </Alert>
    </div>
 // --- JSX bit ----
); }
----

* A React component is a JavaScript function whose name starts with a capital letter. The function returns what should be displayed using JSX syntax.
* A React component name must start with a capital letter. If a component name starts with a lowercase letter, it is treated as a DOM element and won’t render properly. See the following link in the React documentation for more information: https://reactjs.org/docs/jsx-in-dept.html#user-defined-components-must-be-capitalized.
* The filename for component files isn’t important to React or the *React transpiler*. It is common practice to use the same name as the component, either in Pascal or snake case. However, the file extension must be .js or .jsx for React transpilers to recognize these as React components.
* `import` and `export` statements allow JavaScript to be structured into modules. By default, JavaScript code executes in what is called the global scope. Thankfully, JavaScript has a modules feature. A module’s functions and variables are isolated, so functions with the same name in different modules won’t collide.
* A module is a file with at least one export statement.
* Importing a default exported statement must be done with a default `import` statement and the name of the imported default member must be the same as the exported member.

=== Props

* React components have `props` that can be used to customize it. `props` is an optional parameter that is passed into a React component.
* React components using other react components are referred to as `consumers` of the component.
* Destructuring is a JavaScript feature that allows properties to be unpacked from an object. For more information, see the following link: https://developer.mozilla.org/en-US/ docs/Web/JavaScript/Reference/Operators/Destructuring_assignment.
* Props allow a component to be configured by the consuming JSX and are passed as JSX attributes.
* Props are received in the component definition in an object parameter and can then be used in its JSX.

=== State

* The component state is a special variable containing information about the component’s current situation. For example, a component may be in a `loading` state or an `error` state.
* `state` is a key part of making a component interactive. State is defined using a `useState` function from React. The `useState` function is one of React’s *hooks*.

[source]
----
const [state, setState] = useState(initialState);
----

* `useState` returns a tuple containing the current state value and a function to update the state value.
* `useState` returns a *state variable* that can be used to render elements conditionally and a function that can be used to update the value of the state.

* `boolAttr={true}` is equivalent to `boolAttr`.  If the boolean attribute is present on an element, its value is automatically `true`.

=== Events

* React events are a wrapper on top of the browser’s native events.
* A function called an event handler (sometimes referred to as an event listener) can be registered for an element event that contains the logic to execute when that event happens.
* React events are a wrapper on top of the browser’s native events.
* A custom event in a component is implemented by implementing a `prop`. The `prop` is a function that is called to raise the event.
* It is common practice to start an event prop name with `on`.
* Events, along with state, allow a component to be interactive.


=== Quizz Answers

1. Component name starts with lowercase letter.
2. Use `<div>{name}</div>`, also default value for prop, would be a nice touch.
3. Either change prop name to `name` or attribute name to `firstName`.
4. use `onClick` instead of `click`.
5. `true`
6. Need a  boolean value, maybe `useState(false);`  (shit!!!) Correct: call setAgree(true) to change the state.
7. Check if a function is passed as value to `onAgree`, to avoid problems when undefined.
[source]
----
if (onAgree) {
            onAgree();
}
----

== Chapter 2 : Introducing TypeScript

* TypeScript is often referred to as a superset or extension of JavaScript. TypeScript adds a rich type system to JavaScript. It is generally used with frontend frameworks such as Angular, Vue, and React.
* Unlike JavaScript, TypeScript can’t be executed directly in a browser – it must be transpiled into JavaScript first.

=== Basic TypeScript types

* {:typename} - it is referred to as a type annotation.
* TypeScript gives a variable with no type annotation and no immediately assigned value the `any` type.
* Typescript variables initialized with external values, with unsure type can be declared as `unknown`.
* `void` type is used to represent a function’s return type where the function doesn’t return a value.
* The `never` type represents something that will never occur and is typically used to specify unreachable code areas. This is different from `void` because `void` means it will exit, but with no value.

*NOTE:* JavaScript Template literals are enclosed by backticks and can include a JavaScript expression in curly braces prefixed with a dollar sign (`${expression}`). Template literals are great when we need to merge static text with variables.

* `Arrays` are structures that TypeScript inherits from JavaScript. They can be declared in two ways:

[source, typescript]
----
const numbers1: number[] = [];
const numbers2: Array<number> = [];
----

* `object types: { term1: type1; term2: type2 }`
* The `?` symbol is used to make parameters optional, in type and functions declarations.
* A `type alias` refers to another type, and the syntax is as follows: `type YourTypeAliasName = AnExistingType;`

* A type alias can extend another object using the `&` symbol. A type that extends another using the & symbol is referred to as an intersection type.

[source, typescript]
----
type Product = { name: string; unitPrice?: number };
type DiscountedProduct = Product & { discount: number };
----

* A type alias can also be used to represent a function.
[source, typescript]
----
// a function containing a number parameter and doesn’t
// return anything.
type Purchase = (quantity: number) => void;
----

* Object types can be created using TypeScript’s *interface* syntax.