= Learning React

Learning using _Carl Rippon's  Learn React with TypeScript, A beginner's guide to reactive web development with React 18 and TypeScript._

== Package Managers

*Npm* will create node modules globally, if you use some node packages frequently on most of the application you should go for npm.

*npx* locally installs all node packages for a specific project.

*Yarn* is, like NPM, a package manager for Node.JS. Yarn is a different package, but faster than npm and npx. Yarn is built by Facebook. It's faster and has more features than NPM. Their main selling points are:

* *Security*
    ** With `yarn.lock` file (similar to NPM's `npm-shrinkwrap.json`) all dependencies are locked on the exact version. So, you don't have that “But it works on my machine” struggles anymore. Everyone has the same versions locked in `yarn.lock` file
* *Speed*
** Yarn uses (fast) proxies and (offline) caching to deliver your modules faster.

== Create a Project from scratch

Using https://www.npmjs.com[npm] and https://vitejs.dev[vite] a default structure for a React project is easy to generate.

[source]
----
> npm create vite@latest #create react project
----

Choose to create a React project with TypeScript + SWC. https://swc.rs[SWC] SWC is an extensible Rust-based platform for the next generation of fast developer tools, that can be used for both compilation and bundling. For compilation, it takes JavaScript / TypeScript files using modern JavaScript features and outputs valid code that is supported by all major browsers.

After generating the project run:

[source]
----
> npm install
----

Run the app by executing `npm run dev` in a terminal.

Run `npm run lint` to verify your app syntax.

