
= Chapter 5 : Hooks Approaches to Styling React Frontends

[source, shell]
----
npm create vite@latest
cd chapter05
npm install
npm run dev
----

== Plain CSS

* React uses a `className` attribute rather than `class` because `class` is a reserved word in JavaScript. The `className` attribute is converted to a `class` attribute during transpilation.


* The CSS import statement is a `webpack` feature. As webpack processes all the files, it will include all the imported CSS in the bundle.

* The key point here is that webpack doesn’t remove any redundant CSS – *it will include all the content from all the CSS files that have been imported*. This means plain CSS classes are scoped to the whole app and not just the file it is imported into.

== CSS Modules

* CSS modules is an open source library available on GitHub at https://github.com/css-modules/css-modules, which can be added to the webpack process to facilitate the automatic scoping of CSS class names.

* A CSS module is a CSS file, just like in the previous section; however, the filename has an extension of `.module.css` rather than `.css`. This special extension allows webpack to differentiate a CSS module file from a plain CSS file so that it can be processed differently.

* A CSS module file is imported into a React component file as follows:

[source]
----
import styles from './styles.module.css';
----

Styles within a CSS module are referenced in a component’s className attribute as follows:
[source]
----
<span className={styles.error}>A bad error</span>
----

* CSS modules allow CSS class names to be automatically scoped to a React component. This
prevents styles for different React components from clashing.

* CSS modules isn’t a standard browser feature; instead, it is an open source library that can be added to the webpack process.

* *Similar to plain CSS, redundant CSS classes are not pruned from the production CSS bundle.*

== CSS-in-JS

* **CSS-in-JS **isn’t a browser feature, and it isn’t even a specific library – instead, it is a type of library. Popular examples of CSS-in-JS libraries are *styled-components* and *Emotion*.

* Emotion generates styles that are scoped, similar to CSS modules. However, *you write the CSS in JavaScript rather than in a CSS file* – hence the name *CSS-in-JS*. In fact, you can write the CSS directly on JSX elements as follows:

[source, html]
----
<span
    css={css`
        font-weight: 700;
        font-size: 14;
    `}
>
    {text}
</span>
----

* Having styles directly on the component allows a developer to fully understand the component
without having to visit another file.
* This increases the file size, making the code harder to read.
* Child components can be extracted out into specific files to mitigate that.
* A massive benefit of CSS-in-JS is that you can mix logic into the style, which is really useful for highly interactive apps.
* The following example contains a conditional `font-weight` dependent on an `important` prop and a conditional `font-size` dependent on a `mobile` prop. JavaScript string interpolation is used to define the conditional statement.

[source, html]
----
<span
    css={css`
        font-weight: ${important ? 700 : 400};
        font-size: ${mobile ? 15 : 14};
    `}
>
  {text}
</span>
----
This is easier to read than the plain CSS manipulation of two classes:
[source, html]
----
<span
    className={`${important ? "text-important" : ""} ${ mobile ? "text-important" : "" }`}
>
  {text}
</span>
----

Install the `Emotion` library.

[source]
----
npm i @emotion/react
----

* To allow the `css` attribute in React components, the file must start with `/** @jsxImportSource @emotion/react */`.
* The `css` attribute is set to a *tagged template literal*. This is a special string that gets processed by the function specified before it, which is a function called `css` in this case. The tagged template literal converts the style to a CSS class at runtime.

* *This is because Emotion generates the styles at runtime via JavaScript rather than at build time.* If you think about it, the styles can’t be generated at build time because they may depend on JavaScript variables whose values are only known at runtime.

== Using Tailwind CSS

* *Tailwind is a set of prebuilt CSS classes that can be used to style an app*. It is referred to as a *utility-first CSS framework* because the prebuilt classes can be thought of as flexible utilities.

Install the `Tailwind` framework.

[source]
----
npm i -D tailwindcss
npm i -D postcss
npm i -D autoprefixer
----

Next, run the following command in a terminal to generate configuration files for Tailwind and PostCSS:
[source]
----
npx tailwindcss init -p
----

After a few seconds, the two configuration files are created. The Tailwind configuration file is called `tailwind.config.js`, and the PostCSS configuration file is called `postcss.config.js`.

Add configurations for the TSX files in `tailwind.config.js` and edit the `index.css` to add the tailwind directives.

[source]
----
@tailwind base;
@tailwind components;
@tailwind utilities;
----

== Using SVGs

1.Install Vite SVG plugin

[source]
----
npm install vite-plugin-svgr
----

2.Create a file named `svg.d.ts` and add this configuration.

[source]
----
declare module "*.svg" {
  import * as React from "react";

  export const ReactComponent: React.FunctionComponent<
    React.SVGProps<SVGSVGElement> & { title?: string }
  >;
}
----

3.Add this file to the `include` array in `tsconfig.json`.

4.Add `tailwind` configuration into the `vite.config.ts`.

[source]
----
import tailwindcss from 'tailwindcss'

export default defineConfig({
  plugins: [react(), svgr()],

  css: {
    postcss: {
      plugins: [tailwindcss],
    },
  },
})
----

This will make IntelliJ IDEA accept the svg imports.

== Summary

1. plain CSS - applies to all React components
2. CSS modules - scoped css applied only to certain components
3. CSS-in-JS libraries - allows style to be defined directly on the React components
4. Tailwind CSS - reusable CSS classes, *determined at build time*

== Quizz Answers

1.hardcoded - might break the component if the class is removed. Also, maybe change the name to make it component specific to avoid clash with other classes.

2.no. The CSS won’t clash because CSS modules will scope the class names to each component.

3.class name different from the one in the `<div/>` element, should be `styles.wrap`.

4.this way:
[source, react]
----
<button
    css={css`
    border-radius: ${kind === "rounded" ? "4px" : "0px"};
    `}
>
...
</button>
----
5.this way:
[source, react]
----
  const [hovered, setHovered] = useState(false);
  const toggleHover = () => setHovered(!hovered);

   <button aria-label="Close"
                  onMouseEnter={toggleHover}
                  onMouseLeave={toggleHover}
                  className={hovered ? 'bg-blue-700 text-cyan-400 font-bold py-2 px-4 rounded' : 'bg-blue-500 text-white font-bold py-2 px-4 rounded'}>
----
6.this way:
[source, javascript]
----
import { ReactComponent as Logo } from './logo.svg';
----
7.`The bg-${color}-500` class name is problematic because this can only be resolved at
runtime because of the color variable. The used Tailwind classes are determined at build time
and added to the bundle, meaning the relevant background color classes won’t be bundled.
This means that the background color style won’t be applied to the button.